pipeline:
  name: DotNet CI/CD Pipeline
  identifier: DotNetPipeline
  projectIdentifier: my_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build and Deploy
        identifier: BuildAndDeploy
        type: Deployment
        spec:
          service:
            serviceRef: dotnet-service
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: my_k8s_connector
                namespace: default
          execution:
            steps:
              - step:
                  name: Build and Push Docker Image
                  identifier: BuildAndPush
                  type: Run
                  spec:
                    connectorRef: docker_hub
                    image: docker
                    command: |
                      docker build -t mydotnetapp:latest .
                      docker push mydockerhub/mydotnetapp:latest
              - step:
                  name: Deploy to Kubernetes
                  identifier: DeployK8s
                  type: KubernetesDeploy
                  spec:
                    filePaths:
                      - manifests/deployment.yaml
